### ISSUE TITLE
equation in P02-C07 doesn't render correctly

### ISSUE THREAD

**Issue by srochel** [zackchase/mxnet-the-straight-dope#101]
<img width="874" alt="screen shot 2017-08-13 at 10 34 50 am" src="https://user-images.githubusercontent.com/12239237/29251938-3a7faf1a-8013-11e7-9f0a-84d0476cdc76.png">

**Comment by zackchase** [comment]
@smolix  - looks like @srochel found a LaTeX bug. - It's also possible that his browser is slow. Equations show up like this before mathjax renders them ...

**Comment by mli** [comment]
it looks fine for me. please feel free to reopen this issue if this bug still exists
