### ISSUE TITLE
who's awesome?

### ISSUE THREAD

**Issue by soumith** [zackchase/mxnet-the-straight-dope#11]
![480b6216b16fb1a21acc318c3d805f53](https://user-images.githubusercontent.com/1310570/28482266-a10d860c-6e35-11e7-8c80-33cb14bd2e25.jpg)

good stuff. I loved the style of writing the documentation.

**Comment by zackchase** [comment]
:) Thanks @soumith. And thanks for setting a high bar with your really clear intro to PyTorch tutorials.
