### ISSUE TITLE
Slides from KDD'17 tutorial?

### ISSUE THREAD

**Issue by kenahoo** [zackchase/mxnet-the-straight-dope#130]
Hi, I attended the excellent tutorial you did with Alex yesterday at KDD.  You mentioned that the slides will be posted, could you point me to where they will be when so?  Thanks.

**Comment by zackchase** [comment]
Thanks for the feedback! Well definitely post the slides: @smolix, @mli where's the best place to do this in the next hrs?

**Comment by zackchase** [comment]
Hi @kenahoo - I've uploaded the slides (both as KeyNote and PDF) to a Github repo: 
https://github.com/zackchase/mxnet-slides

**Comment by kenahoo** [comment]
Thanks!
