### ISSUE TITLE
how to get the parameter value after I initialize it

### ISSUE THREAD

**Issue by SherlockLiao** [zackchase/mxnet-the-straight-dope#150]
```python
import mxnet as mx
import mxnet.gluon as g

ctx = mx.gpu()
net = g.nn.Sequential()
with net.name_scope():
    net.add(g.nn.Dense(10, in_units=100))

net.collect_params().initialize(mx.init.Xavier(), ctx=ctx)
```
If I define network like this, I run this script, I will encouter a problem.

I also don't know how to get the weight value.

**Comment by mli** [comment]
```python
dense = net[0] # get the first layer
W = dense.params.get('weight') # get W
print(type(W.data())) # get the value (copied to CPU if necessary)
print(W.data(ctx=ctx).context) # get the value on GPU 0
```

**Comment by piiswrong** [comment]
You can do 
```W = dense.weight``` directly

**Comment by SherlockLiao** [comment]
@piiswrong But I can only get the following information `Parameter dense0_weight (shape=(20, 0), dtype=<class 'numpy.float32'>)`, I want to get the exact values.

I have a method, I define a network, and define a random input, then feed forward, and use `model.collect_params()['params'].data()` can get the exact result.

I don't know if there are other methods can do.

**Comment by mli** [comment]
try 
```
dense.weight.data()
```

**Comment by SherlockLiao** [comment]
if I just run `dense.weight.data()`, it will encounter `RuntimeError: Parameter dense0_weight has not been initialized`.
I run initialize, then I can get the result by `dense.weight.data()`.
