### ISSUE TITLE
P01-C04 render & math problem

### ISSUE THREAD

**Issue by t103z** [zackchase/mxnet-the-straight-dope#157]
- Jupyter throws error when loading the page. It seems to be fine in the last commit.
- Section *Conditional Probability*, 0.01 \* 0.03 should be 0.0003

**Comment by DanielTakeshi** [comment]
P01-C04 has additional issues. If you look at the notebook:

https://github.com/zackchase/mxnet-the-straight-dope/blob/master/P01-C04-probability.ipynb

There's an `mnist` variable which is used before it's defined, which seems to be related to the other errors you see later.

**Comment by zackchase** [comment]
Hi @t103z and @DanielTakeshi, sorry for the delay and thanks to bearing with us. I believe everything should work now. I rewrote the first half of the probability section and might trim down some of the second half to keep the material focused. Please re-open if anything is still broken (note that the URL structure has changed for the whole book).
