### ISSUE TITLE
TOC link missing in preface

### ISSUE THREAD

**Issue by jhyearsley** [zackchase/mxnet-the-straight-dope#167]
The table of contents (TOC) link is missing in the first notebook. I've forked the repo and will submit a pull request. I decided to set the link to the TOC for *this* repo. This seems like the first solution. That being said, one could envision the link going to the TOC for each individuals forked repo but I won't do that at the moment.

**Comment by jhyearsley** [comment]
Oh wait, never mind, probably makes more sense to link to the actual documentation website (as opposed to the github repo). I will make this change.

**Comment by zackchase** [comment]
Sorry not to reply here in writing. I read it but at the time was still working out how to reorganize the material. The solution now is to have the footers of all notebooks point to the next book. That seems more reasonable than referencing people back to TOC :). Every notebook in the first 8 chapters should be linked to its successor now.
