### ISSUE TITLE
various feedbacks

### ISSUE THREAD

**Issue by eric-haibin-lin** [zackchase/mxnet-the-straight-dope#199]
### Empty lines at the bottom 
<img width="756" alt="screen shot 2017-09-09 at 10 38 42 am" src="https://user-images.githubusercontent.com/5545640/30242424-12a0b76c-954b-11e7-9ace-4df1eceeb4af.png">

- [x] [probability](http://thestraightdope.mxnet.io/chapter01_crashcourse/probability.html)
- [x] [linear-regression-scratch](http://thestraightdope.mxnet.io/chapter02_supervised-learning/linear-regression-scratch.html)
- [x] [training-with-multiple-machines](http://thestraightdope.mxnet.io/chapter07_distributed-learning/training-with-multiple-machines.html)
- [x] [perceptron](http://thestraightdope.mxnet.io/chapter02_supervised-learning/perceptron.html)

### Error messages too long to fit in the screen
<img width="831" alt="screen shot 2017-09-09 at 10 39 48 am" src="https://user-images.githubusercontent.com/5545640/30242433-3fa6d548-954b-11e7-81b5-4bf7f4f126c5.png">

- [ ] [linear-regression-gluon](http://thestraightdope.mxnet.io/chapter02_supervised-learning/linear-regression-gluon.html)

### Typos
- [ ] [linear-regression-gluon](http://thestraightdope.mxnet.io/chapter02_supervised-learning/linear-regression-gluon.html)
`However, the actual initialization is deferred until the shapes have been deferred.` -> `shapes have been *inferred*`

### Broken Links
- [ ] [training-with-multiple-machines](http://thestraightdope.mxnet.io/chapter07_distributed-learning/training-with-multiple-machines.html)
  `As mentioned in multiple-gpu-scratch ` -> link for multiple-gpu-scratch is not valid.

**Comment by zackchase** [comment]
Thanks Haibin. Good eyes. Please let me know if you find any more!

**Comment by zackchase** [comment]
Fixed!

**Comment by eric-haibin-lin** [comment]
@zackchase one more blank line at the bottom: http://thestraightdope.mxnet.io/chapter07_distributed-learning/multiple-gpus-gluon.html

**Comment by eric-haibin-lin** [comment]
And a blank line at the bottom here... http://thestraightdope.mxnet.io/chapter07_distributed-learning/hybridize.html

**Comment by zackchase** [comment]
Noted.

**Comment by zackchase** [comment]
Fixed.
