### ISSUE TITLE
Typo ?

### ISSUE THREAD

**Issue by leo-mon** [zackchase/mxnet-the-straight-dope#20]
https://github.com/zackchase/mxnet-the-straight-dope/blob/b964214a3b4223932d6076d0dcec3e0e66b17b9f/P02-C03-softmax-regression-scratch.ipynb#L76

`train-label` might be `train_label` ?

Thank you so much for nice tutorials for the beginner like me.

**Comment by zackchase** [comment]
Thanks for the keen eyes :). It makes it a lot easier to undertake a project like this when we have nice people like you helping us out. Grateful for this and any other feedback as you go.

**Comment by zackchase** [comment]
Fixed
