### ISSUE TITLE
Missing ipython notebook download button?

### ISSUE THREAD

**Issue by eric-haibin-lin** [zackchase/mxnet-the-straight-dope#232]
One good-to-have thing I find missing in the straight dope book is that I don't find a button to download an ipython notebook file from the website and play with it. I do know there's a page for instructions to run the tutorials, but a download button like the one in mxnet basic tutorials (e.g https://mxnet.incubator.apache.org/versions/master/tutorials/basic/ndarray.html) will be great.

**Comment by zackchase** [comment]
@eric-haibin-lin, I agree that would be great,. can you implement it and make a PR? Easiest way is just to download the notebook source from GitHub.

**Comment by zackchase** [comment]
@eric-haibin-lin  --- checking on this. Eric any interest in building this @mli -- you know the build process better than anyone. How hard would this be to implement?
