### ISSUE TITLE
Cannot update self with other because they have different Parameters with the same name deep_dog_conv0_weight

### ISSUE THREAD

**Issue by wzhang1** [zackchase/mxnet-the-straight-dope#238]
mxnet-the-straight-dope/chapter08_computer-vision/fine-tuning.ipynb
cpu mode, when running the traning cell, got the following error:

AssertionError                            Traceback (most recent call last)
<ipython-input-46-901ef48098ac> in <module>()
     62     #print(deep_dog_net)
     63     #print(deep_dog_net.collect_params())
---> 64     deep_dog_net.collect_params().reset_ctx(contexts)
     65     train(deep_dog_net, train_iter, val_iter, epochs, contexts)

/usr/local/lib/python2.7/dist-packages/mxnet/gluon/block.pyc in collect_params(self)
    211         ret.update(self.params)
    212         for cld in self._children:
--> 213             ret.update(cld.collect_params())
    214         return ret
    215 

/usr/local/lib/python2.7/dist-packages/mxnet/gluon/parameter.pyc in update(self, other)
    492                 assert self._params[k] is v, \
    493                     "Cannot update self with other because they have different " \
--> 494                     "Parameters with the same name %s"%k
    495             else:
    496                 self._params[k] = v

AssertionError: Cannot update self with other because they have different Parameters with the same name deep_dog_conv0_weight

**Comment by zackchase** [comment]
@szha can you please fix this - I think this is related to a change in the naming convention of conv layers in the prelease that also affected our distributed tutorials.

**Comment by szha** [comment]
Taking a look

**Comment by szha** [comment]
@wzhang1 could you upgrade your mxnet to the latest version?
```bash
pip install mxnet -U --pre --user
```

**Comment by wzhang1** [comment]
@szha it seems that in the ubuntu 16.04 I'm using, I got the following result for os.path.exists


Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2

>>> os.path.exists("/home/w/.mxnet/models/squeezenet1.1-33ba0f93.params")
True
>>> os.path.exists("~/.mxnet/models/squeezenet1.1-33ba0f93.params")
False

**Comment by szha** [comment]
`os.path.expanduser` is used for expanding `~`. I'm not sure how this is relevant.

**Comment by wzhang1** [comment]
@szha I remove a optional variable in line 132 and the model is loaded for me
 net.load_params(get_model_file('squeezenet%s'%version), ctx=ctx)

https://github.com/apache/incubator-mxnet/blob/master/python/mxnet/gluon/model_zoo/vision/squeezenet.py

**Comment by wzhang1** [comment]
@szha or add net.load_params   in get_squeezenet, which way do you prefer?

**Comment by wzhang1** [comment]
@szha I went to to look the changes and found similar issue for other networks, should be a small fix

https://github.com/apache/incubator-mxnet/pull/7892/commits/dfd1bb960b8346ee9032480160cfcb85764d1407

**Comment by wzhang1** [comment]
closing, default location issue moved to /mxnet/gluon/model_zoo/vision

**Comment by wzhang1** [comment]
Thank you everyone!
