### ISSUE TITLE
Is there a resnet in gluon?

### ISSUE THREAD

**Issue by KeyKy** [zackchase/mxnet-the-straight-dope#251]

**Comment by zackchase** [comment]
You can find one among the examples in the mxnet codebase proper. We will add a resnet to the book soon

**Comment by piiswrong** [comment]
https://mxnet.incubator.apache.org/versions/master/api/python/gluon/gluon.html#resnet

Gluon has all sorts of net built in

**Comment by KeyKy** [comment]
Thanks
