### ISSUE TITLE
Doesn't print mxnet.ndarray.NDArray

### ISSUE THREAD

**Issue by deehzee** [zackchase/mxnet-the-straight-dope#27]
Following the tutorial at http://thestraightdope.mxnet.io/P01-C02-ndarray.html

Versions:
* Python 2.7.13
* mxnet 0.10.0

In input line 2, the print command doesn't display the content of the ndarray `x`:
```ipython
In[2]: x = nd.empty(shape=(6,4))
  ...: print(x)
```
Instead of showing the content, it shows:
```
<NDArray 6x4 @cpu(0)>
```

I needed to use `print(x.asnumpy())` to show the content.

**Comment by zackchase** [comment]
Yeah, this was also an issue that's been resolved but not in the stale version you get from pip. Building from source will solve everything. Don't forget to build with CUDA=1 if you plan on using GPU :)
