### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by srochel** [zackchase/mxnet-the-straight-dope#271]
Link at end of https://github.com/zackchase/mxnet-the-straight-dope/blob/master/chapter02_supervised-learning/regularization-gluon.ipynb to loss.ipynb does not exist.

**Comment by sebg** [comment]
Issue fixed by c1aa851c5fb7d12ad2064639a6991e42f71cfce6

Link changed from
=> `"[Loss functions](../chapter02_supervised-learning/loss.ipynb)"`

to
=> `"[Learning environments](../chapter02_supervised-learning/environment.ipynb)"`

Suggest @zackchase can close this issue.

**Comment by zackchase** [comment]
Thanks @sebg
