### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by eric-haibin-lin** [zackchase/mxnet-the-straight-dope#273]
The link to the next chapter doesn't work

http://gluon.mxnet.io/chapter07_distributed-learning/multiple-gpus-scratch.html#Next

<img width="679" alt="screen shot 2017-10-08 at 6 11 56 pm" src="https://user-images.githubusercontent.com/5545640/31322891-318d247e-ac54-11e7-9f95-bff94bae7097.png">

**Comment by sebg** [comment]
Issue appears to be cause by having a code block with gluon in the link.  There are two ` before and after the word, so it causes a break between how it renders in github and how it renders at gluon.xmnet.io

It works fine in 
https://github.com/zackchase/mxnet-the-straight-dope/blob/67b5a9e5a6c4c3170adda40a1cd6a2a001949ba5/chapter07_distributed-learning/multiple-gpus-scratch.ipynb

but breaks on

http://gluon.mxnet.io/chapter07_distributed-learning/multiple-gpus-scratch.html#Next

simplest fix would be to remove code block and leave gluon on it's own.

if @zackchase 's okay with this change, happy to go in and remove code block.

**Comment by zackchase** [comment]
Fixed. Thanks @eric-haibin-lin and @sebg
