### ISSUE TITLE
Multi-GPU training example code has error

### ISSUE THREAD

**Issue by xiaogehh** [zackchase/mxnet-the-straight-dope#274]
![qq 20171009132545](https://user-images.githubusercontent.com/7589403/31325987-b3ae32da-acf5-11e7-8f91-20ed546f023a.png)

When running this code in [Training on multiple GPUs with gluon](http://gluon.mxnet.io/chapter07_distributed-learning/multiple-gpus-gluon.html),it has error.

**Comment by zackchase** [comment]
Fixed.
