### ISSUE TITLE
A typo in chapter 01 introduction

### ISSUE THREAD

**Issue by Jing-Luo** [zackchase/mxnet-the-straight-dope#278]
In the second paragraph of sequence learning section, there is a typo:

> What how wuold we deal with video snippets?

Guess it should be

> How would we deal with video snippets?

**Comment by Jing-Luo** [comment]
Also, in the Automatic Speech Recognition section,

> Tese are seq2seq problems where the output is much shorter than the input.
should be

> These are seq2seq problems where the output is much shorter than the input.

**Comment by Jing-Luo** [comment]
Another one is in the Serialization part:
http://gluon.mxnet.io/chapter03_deep-neural-networks/serialization.html
Guess it should use cpu as it used to be?

**Comment by sebg** [comment]
Typo:
> What how wuold we deal with video snippets?
has been fixed.

Typo:
> Tese are seq2seq problems where the output is much shorter than the input.
has been fixed.

Typo in Serialization part:
couldn't find it.

As such - suggest @zackchase can close this issue.

**Comment by zackchase** [comment]
Thanks @sebg
