### ISSUE TITLE
Problem in head gradients of autograd

### ISSUE THREAD

**Issue by Jing-Luo** [zackchase/mxnet-the-straight-dope#280]
When running the code in autograd section http://gluon.mxnet.io/chapter01_crashcourse/autograd.html:

```
with autograd.record():
    y = x * 2
    z = y * x

head_gradient = nd.array([[10, 1.], [.1, .01]])
z.backward(head_gradient)
print(x.grad)
```

The result is:
[[ 40.           8.        ]
 [  1.20000005   0.16      ]]
<NDArray 2x2 @cpu(0)>

Have you noticed why it is 1.20000005 instead of 1.2? I feel quite puzzled.

**Comment by zackchase** [comment]
This looks like typical approximation noise due to doing low precision math. @szha - agree?

**Comment by szha** [comment]
Yes. Float is not accurate. There are plenty of readings on this on the internet.

```python
In [1]: i = 16777216.0

In [2]: for _ in xrange(int(1e9)):
   ...:     i += 1e-9

In [3]: i
Out[3]: 16777216.0
```
You'd expect `i=16777217.0` but you will get 16777216.0 instead.

And here's a video on how float behaves if you have 15min to spare, which explains why such weirdness happens: https://www.youtube.com/watch?v=pQs_wx8eoQ8

**Comment by Jing-Luo** [comment]
Oh, thanks very much! I have thought it is an approximation noise but cannot figure out why it occurs in such an easy operation (12 * 0.1) haha~
