### ISSUE TITLE
Add link to document website to the repo introduction.

### ISSUE THREAD

**Issue by zhreshold** [zackchase/mxnet-the-straight-dope#30]
How about adding the link to the introduction, google is showing multiple domains related.

BTW, P02-C06 will timeout when `make html` because it's using 1000 epochs. Better have results stored in advance, otherwise `nbsphinx_timeout = 600` is required in `conf.py`

**Comment by mli** [comment]
fixed by https://github.com/zackchase/mxnet-the-straight-dope/commit/d153ab09636a7474fc1cca861e52d55aea5791f4
