### ISSUE TITLE
[WIP] Cheatsheet for Pytorch to Gluon

### ISSUE THREAD

**Issue by szha** [zackchase/mxnet-the-straight-dope#301]
The goal is to provide a concise set of reference for existing pytorch user to adopt gluon.

# How to contribute
1. pick a section that's not being worked on (fork subsections if necessary, discuss in this issue first)
2. comment on this issue stating that you're working on section x.x
3. write a paragraph to describe high-level similarity and differences. For example:
```
Placeholder for description, highlights of similarity and differences
- Lorem ipsum dolor sit amet, consectetur adipiscing elit.
- Vestibulum commodo est et diam volutpat molestie.
```
4. write a table that looks like the following. fill in the table with code snippets.
```
| Function               | Pytorch                           | MXNet Gluon                              |
|------------------------|-----------------------------------|------------------------------------------|
| Copy to GPU            | `y = torch.FloatTensor(1).cuda()` | `y = mxnet.nd.ones((1,), ctx=mx.gpu(0))` |
| Convert to numpy array | `x = y.cpu().numpy()`             | `x = y.asnumpy()`                        |
```
5. keep everything short and concise.

The above will render to:
------------------
Placeholder for description, highlights of similarity and differences
- Lorem ipsum dolor sit amet, consectetur adipiscing elit.
- Vestibulum commodo est et diam volutpat molestie.

| Function               | Pytorch                           | MXNet Gluon                              |
|------------------------|-----------------------------------|------------------------------------------|
| Copy to GPU            | `y = torch.FloatTensor(1).cuda()` | `y = mxnet.nd.ones((1,), ctx=mx.gpu(0))` |
| Convert to numpy array | `x = y.cpu().numpy()`             | `x = y.asnumpy()`                        |
------------------

The file to edit is https://github.com/zackchase/mxnet-the-straight-dope/blob/master/cheatsheets/pytorch_gluon.md

# Progress
- [x] 1. Pytorch Tensor and MXNet NDArray
  - [x] 1.1. Tensor operation
  - [x] 1.2. Functional
  - [x] 1.3. GPU (by @szha)
  - [x] 1.4. cross device (by @ZiyueHuang)

- [x] 2. Autograd (by @ZiyueHuang)
  - [x] 2.1. variable wrapper vs autograd scope
  - [x] 2.2. gluon can supply head grad
  - [x] 2.3. scope override (pause, train_mode, predict_mode)
  - [x] 2.4. batch-end synchronization is needed

- [x] 3. Pytorch module and Gluon blocks
  - [x] 3.1. usage of existing blocks look alike
  - [x] 3.2. for new block definition, gluon needs name_scope
  - [x] 3.3. HybridBlock can be hybridized, and allows partial-shape info
  - [x] 3.4. SymbolBlock
  - [x] 3.5. Parameter and Initializer

- [x] 4. Pytorch optimizer vs Gluon Trainer
  - [x] 4.1. for gluon zero_grad is not necessary most of the time
  - [x] 4.2. for gluon zero_grad only needed when `grad_req` is `'add'`
  - [x] 4.3. Multi-GPU training
  - [x] 4.4. Distributed training

- [x] 5. Monitoring
  - [x] 5.1. MXNet has pre-defined metrics
  - [x] 5.2. Data visualization

- [x] 6. I/O and deploy
  - [x] 6.1. Data loading
  - [x] 6.2. Serialization

**Comment by szha** [comment]
I worked on 1.3 in #302

**Comment by ZiyueHuang** [comment]
I will work on 1.4 `cross device`.

**Comment by zhreshold** [comment]
I will take 6.

**Comment by zackchase** [comment]
Great! Thanks guys!

**Comment by Jerryzcn** [comment]
working on 1.1 & 1.2

**Comment by ZiyueHuang** [comment]
working on section 2 `Autograd `

**Comment by ZiyueHuang** [comment]
working on section 3 `Pytorch module and Gluon blocks`

**Comment by SherlockLiao** [comment]
maybe can add an item about initializer and shape infer between pytorch and gluon @szha

**Comment by szha** [comment]
Good idea. I added a section 3.5 on parameter and initializer. Partial shape is included in 3.3.
Suggestions are welcome.

**Comment by SherlockLiao** [comment]
I will take the initializer section first.

**Comment by szha** [comment]
Ping

**Comment by ZiyueHuang** [comment]
working on sec 4.1 and sec 4.2

**Comment by szha** [comment]
Thank you so much guys for your contribution. We're finally ready to close this issue now.
