### ISSUE TITLE
z is the function of both y and x

### ISSUE THREAD

**Issue by ShawnXuan** [zackchase/mxnet-the-straight-dope#31]
about *Head gradients and the chain rule* in [P01-C05-autograd](https://github.com/zackchase/mxnet-the-straight-dope/blob/master/P01-C05-autograd.ipynb) . $z$ is the function of both $y$ and $x$.
$$
\frac {dz(y,x)}{dx} 
= \frac {dz}{dy} \frac {dy}{dx} +\frac {dz}{dx}
= 2x + y = 4x
$$

**Comment by wlike** [comment]
Also confused with the example. According to the code in `with ag.record()`, dz/dx = 4x. And x = [[1,2], [3,4]], so the result is [[4,8], [12, 16]]. What's the purpose of head gradients of dz/dy?

**Comment by orchidmajumder** [comment]
I have opened an issue to improve the documentation. Basically, if you want to understand the notion of head gradient, I believe this http://cs231n.github.io/optimization-2/ might be useful, where it explains the concept with the notion of local and incoming gradient. @wlike
