### ISSUE TITLE
typos and errors

### ISSUE THREAD

**Issue by ZiqianXie** [zackchase/mxnet-the-straight-dope#338]
In ndarray.html#Managing-context, 

> So we want you to be 100% certian that

In perceptron.html, the direction of inequality which bounds ||(w_{t+1}, b_{t+1})|| is wrong, and a right parenthesis is missing.

**Comment by zackchase** [comment]
on which line is the right parenthesis missing?

**Comment by zackchase** [comment]
Can you either give a line number or even better open a PR :)
