### ISSUE TITLE
Typo? : Crash Course > Linear Algebra > Scalars

### ISSUE THREAD

**Issue by netgio** [zackchase/mxnet-the-straight-dope#351]
Text (from source markup) says... "If you wanted to convert this value to Celsius (the more sensible metric system temperature measurement), you'd evaluate the expression $c = (52 - 32) * 5/9$ setting $f$ to $52$"

but there is no "f" to set in the expression.

Suggest it should be:
"If you wanted to convert this value to Celsius (the more sensible metric system temperature measurement), you'd evaluate the expression $c = (**$f$** - 32) * 5/9$ setting $f$ to $52$"

**Comment by zackchase** [comment]
Yeah my bad I let that slip in by merging a *mostly correct PR*. Will fix

**Comment by zackchase** [comment]
Fixed
