### ISSUE TITLE
formulas in Sums and means section of P01-C03-linear-algebra.ipynb are ill formatted

### ISSUE THREAD

**Issue by srochel** [zackchase/mxnet-the-straight-dope#37]
Currently: 
A related quantity to the sum is the mean, also commonly called the average. We calculate the mean by dividing the sum by the total number of elements. With mathematical notation, we could write the average over a **vector ${\boldsymbol{u}$ as \frac{1}{d} \sum_{i=1}^{d} ui$ and the average over a matrix $A$ as  $\frac{1}{n \cdot m} \sum{i=1}^{m} \sum{j=1}^{n} a{i,j}$.** In code, we could just call nd.mean() tensors of arbitrary shape:

**Comment by zackchase** [comment]
I don't see the bug. It appears to look wrote in my notebook and on .io. am I missing smtg?

**Comment by bhavinthaker** [comment]
I see the same rendering problem as @srochel. Here is how the page renders on Chrome, Safari and Firefox for me:
<img width="720" alt="screen shot 2017-07-29 at 5 42 20 pm" src="https://user-images.githubusercontent.com/6851302/28749716-c31135b8-7485-11e7-8f5a-3cf837a1cf85.png">

@zackchase I think the dollar and curly-braces do not seem to have matching begin and end occurrences. 
May be extra { in =>  ${\\boldsymbol 
Missing $ at the start of =>  \\frac{1}{d} \\sum_{i=1}^{d} u_i$ 

"source": [
    "A related quantity to the sum is the *mean*, also commonly called the *average*. We calculate the mean by dividing the sum by the total number of elements. With mathematical notation, we could write the average over a vector ${\\boldsymbol{u}$ as \\frac{1}{d} \\sum_{i=1}^{d} u_i$ and the average over a matrix $A$ as  $\\frac{1}{n \\cdot m} \\sum_{i=1}^{m} \\sum_{j=1}^{n} a_{i,j}$. In code, we could just call ``nd.mean()`` tensors of arbitrary shape:"
