### ISSUE TITLE
CNN penultimate layer

### ISSUE THREAD

**Issue by patriciaaa82** [zackchase/mxnet-the-straight-dope#372]
Hi!
Is there an easy way to obtain the weights of the penultimate layer of a CNN using gluon?
Thanks

**Comment by zackchase** [comment]
If it's a sequential you can grab any layer just by doing net[i]. Grab it's parameters by calling net[i].collect_params()

**Comment by patriciaaa82** [comment]
Thanks!

**Comment by patriciaaa82** [comment]
Hi, yet another question.

Imagine I have a pre-trained CNN for image prediction. If I understand correctly: 
net(image) -> gives the prediction. 

But, how can I get the evaluation of the penultimate layer (or any layer), given the image?

Thanks
Patricia
