### ISSUE TITLE
chapter08 fine_tuning doesn't work

### ISSUE THREAD

**Issue by QiXuanWang** [zackchase/mxnet-the-straight-dope#423]
Edit: only 1 issue due to squeezenet1_1 change:
1. net.classifier[1]: there is no classifier method in squeezenet1_1 anymore. I replaced it with net.output[0] instead

**Comment by zackchase** [comment]
@szha can you please take a look and update it to be compatible with latest mxnet/model zoo? Thanks!!

**Comment by szha** [comment]
On it.

**Comment by zackchase** [comment]
Thanks @szha!!
