### ISSUE TITLE
gluon.mxnet.io HTTPS

### ISSUE THREAD

**Issue by ThomasDelteil** [zackchase/mxnet-the-straight-dope#466]
It would be nice to have gluon.mxnet.io HTTPS enabled

![screen shot 2018-04-13 at 12 36 02 pm](https://user-images.githubusercontent.com/3716307/38754593-542ce086-3f17-11e8-8192-1e3e5823000c.png)

**Comment by zackchase** [comment]
@mli @szha what do we need to do to get gluon.mxnet.io on https ?

**Comment by zackchase** [comment]
@astonzhang @piiswrong

**Comment by szha** [comment]
https should redirect to http url. having https for a static website with no sensitive user input is a waste of certificate.

**Comment by ThomasDelteil** [comment]
@szha I whole-heartedly disagree. There are several good reasons why you want your content to be HTTPS, especially when users are downloading code. 

- **Man in the middle attack**, you wouldn't notice if someone is intercepting your traffic and replacing one notebook for another with malicious code.

- **SEO page boost** from Google for using HTTPS

- **Trust increase from using HTTPS**, rather than the "unsecure" showed on Chrome. From july 2018, Chrome will mark every http website as "unsecure".

- **Spy on your traffic and area of research**, http is a breach of privacy for people/journalists who wants their area of research to remain private.

**Comment by szha** [comment]
@ThomasDelteil OK I'm sold. @mli

**Comment by ThomasDelteil** [comment]
Awesome, I confirm that it is working.
