### ISSUE TITLE
Stop slacking off

### ISSUE THREAD

**Issue by skaldesh** [zackchase/mxnet-the-straight-dope#566]
I read [chapter 08](https://gluon.mxnet.io/chapter08_computer-vision/fine-tuning.html) of computer vision on gluon.mxnet.io. It told me to open this issue, since record files have not been introduced in these tutorials yet. See paragraph *Files*  

Quote from it:  
> We prepare the dataset in the format of MXRecord using im2rec tool. As of the current draft, rec files are not yet explained in the book, but if you’re reading after November or December 2017 and you still see this note, open an issue on GitHub and let us know to stop slacking off.

**Comment by vishaalkapoor** [comment]
:) 

As mentioned in the README.md this book has been moved into to d2l.ai. Please see https://d2l.ai/chapter_computer-vision/index.html particularly

https://d2l.ai/chapter_computer-vision/object-detection-dataset.html?highlight=im2rec
