### ISSUE TITLE
network visualization

### ISSUE THREAD

**Issue by SmartAILM** [zackchase/mxnet-the-straight-dope#57]
How to visualize network created by gluon, since ```mx.viz.plot_network``` can just visulize ```symbol```

**Comment by mli** [comment]
just `print`

say `net = nn.Sequential()` `net.add(...)`, then just `print(net)`

another way is using `hybridize` to get the symbol, and then use the existing `plot_network`

**Comment by thomelane** [comment]
I was looking to do the same thing, so thought I'd leave some code as reference, using @mli's idea to hybridize to get the symbol;

```
import mxnet as mx

net = mx.gluon.nn.HybridSequential()
with net.name_scope():
    net.add(mx.gluon.nn.Dense(256, activation="relu"))
    net.add(mx.gluon.nn.Dense(256, activation="relu"))
    net.add(mx.gluon.nn.Dense(10))
    
# Option 1    
print(net)

# Option 2 (net must be HybridSequential, if want to plot whole graph)
net.hybridize()
net.collect_params().initialize()
x = mx.nd.random_normal(shape=(16, 1, 28, 28))
net(x)
mx.viz.plot_network(net._cached_graph[1])
```

**Comment by orchidmajumder** [comment]
For Gluon, this seems to work:
``
x = mx.sym.var('data')
sym = net(x)
a = mx.viz.plot_network(sym)
a.render("test_plot.gv", view=True)

``

**Comment by relaxli00** [comment]
for the latest Gluon with mxnet np_array and npx, after hybridize, the code should be:

```
x = mx.sym.var('data')
sym = net(x.as_np_ndarray())
a = mx.viz.plot_network(sym)
a.render("test_plot.gv", view=True)
```
