### ISSUE TITLE
Print the whole training process

### ISSUE THREAD

**Issue by wlike** [zackchase/mxnet-the-straight-dope#65]
http://gluon.mxnet.io/P05-C03-lstm-scratch.html

In this tutorial, printing the whole the training process, which is useless

http://gluon.mxnet.io/P05-C05-gru-scratch.html

In this tutorial, the name is still Long Short-Term Memory

**Comment by zackchase** [comment]
Hey thanks for the catches - yes theres are very early drafts. Just getting the skeleton in there and making sure all the code is working. Those two don't yet have any exposition. I think I might label each chapter according to its stage of completion maybe somthing like {dogfood, alpha, beta, palatable}. Could potentially have two indicators for exposition and code respectively.

**Comment by zackchase** [comment]
Fixed text reference to LSTM - holding off on killing printouts. 

Re the latter I actually think - when you implement language models from scratch, it's quite instructive to see how it gradually starts putting together words over the course of training. Will think of a more elegant way to set this up when I next revisit it.
