### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by juliensimon** [zackchase/mxnet-the-straight-dope#73]
http://gluon.mxnet.io/
"More detailed instructions are available here"
--> http://gluon.mxnet.io/docs/C01-install.rst doesn't exist

http://gluon.mxnet.io/P02-C01-linear-regression-scratch.html
"First, we’ll import the same dependencies as in the autograd tutorial"
--> http://gluon.mxnet.io/2-autograd.ipynb doesn't exist

**Comment by zackchase** [comment]
Thanks, I'll fix these.

**Comment by zackchase** [comment]
Fixed.
