### ISSUE TITLE
[Need fix] Use block.save_params() instead of block.collect_params().save()

### ISSUE THREAD

**Issue by szha** [zackchase/mxnet-the-straight-dope#81]
In gluon, net.collect_params().save() won't automatically strip the model prefix in parameters. This would prevent the checkpoint files from being loaded into models with different prefixes. The net.save_params() strips the prefix before saving. Going forward, please use block.save_params() and block.load_params().

The following notebooks need to be fixed:
P05-C04-rnns-gluon.ipynb
P06-C03-object-detection.ipynb
P14-C05-hybridize.ipynb

**Comment by zackchase** [comment]
Great. Can you fix the notebooks and make a PR?
